// @mdbrian/wiki-engine — Map & Pointer generator (OpenWiki pattern).
//
// Generates a "## MDBrain Wiki Map" block listing the wiki pages an agent
// should read before large tasks, and injects it idempotently into a repo's
// AGENTS.md / CLAUDE.md (or any markdown file). Re-running updates the block
// in place, preserving the rest of the file.
//
// T8.

import { listWikiPages, type WikiDbHandle } from "./wiki-bridge.js"

// ---------------------------------------------------------------------------
// Block generation
// ---------------------------------------------------------------------------

const BLOCK_START = "<!-- MDBRAIN-WIKI-MAP:START -->"
const BLOCK_END = "<!-- MDBRAIN-WIKI-MAP:END -->"

export interface MapPointerOptions {
	/** Filter pages by kind (entity/concept/synthesis/source/report/procedure). */
	kind?: string
	/** Filter pages by scope. */
	scope?: string
	/** Filter pages by scopeRef. */
	scopeRef?: string
	/** Max pages to list. Default 50. */
	maxPages?: number
	/** Header text for the block. Default "## MDBrain Wiki Map". */
	heading?: string
}

/** Generates the markdown block content (between the START/END markers). */
export function buildWikiMapBlock(
	pages: Array<{ title: string; slug: string; summary: string }>,
	opts: MapPointerOptions = {},
): string {
	const heading = opts.heading ?? "## MDBrain Wiki Map"
	const lines: string[] = [BLOCK_START, heading, ""]
	if (pages.length === 0) {
		lines.push(
			"_No wiki pages found. Run `mdbrian wiki apply` or import an OKF bundle to populate the map._",
		)
		lines.push("")
	} else {
		for (const p of pages) {
			const summary = p.summary ? ` — ${p.summary.split("\n")[0]}` : ""
			lines.push(`- **[${p.title}](wiki/${p.slug})** \`${p.slug}\`${summary}`)
		}
		lines.push("")
	}
	lines.push(
		`_Auto-generated by \`mdbrian init\`. Re-run to refresh. ${pages.length} page(s)._`,
	)
	lines.push(BLOCK_END)
	return lines.join("\n")
}

/** Fetches wiki pages from MongoDB and builds the map block. */
export async function generateWikiMapBlock(
	handle: WikiDbHandle,
	opts: MapPointerOptions = {},
): Promise<string> {
	const maxPages = opts.maxPages ?? 50
	const result = await listWikiPages(handle, {
		kind: opts.kind,
		scope: opts.scope,
		scopeRef: opts.scopeRef,
		limit: maxPages,
	})
	const pages = result.pages.map((p) => ({
		title: p.title,
		slug: p.slug,
		summary: p.summary,
	}))
	return buildWikiMapBlock(pages, opts)
}

// ---------------------------------------------------------------------------
// Idempotent file injection
// ---------------------------------------------------------------------------

/** Injects (or updates) the wiki map block in a markdown file's content.
 *  Preserves everything outside the START/END markers. Returns the new
 *  content. If the file has no existing block, appends it at the end. */
export function injectWikiMapBlock(fileContent: string, block: string): string {
	const startIdx = fileContent.indexOf(BLOCK_START)
	const endIdx = fileContent.indexOf(BLOCK_END)
	if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
		// Replace the existing block.
		const before = fileContent.slice(0, startIdx)
		const after = fileContent
			.slice(endIdx + BLOCK_END.length)
			.replace(/^\n/, "")
		// Preserve a trailing newline (L3: replaced block at EOF dropped it).
		return `${before}${block}${after ? "\n" + after : "\n"}`
	}
	if (startIdx !== -1 && (endIdx === -1 || endIdx < startIdx)) {
		// Malformed: START without END (or END before START). Strip from START
		// to EOF (removes the orphan) and append a clean block — avoids the
		// duplicate-marker issue (M1).
		const before = fileContent.slice(0, startIdx).replace(/\n+$/, "")
		return before ? `${before}\n\n${block}\n` : `${block}\n`
	}
	// No existing block — append at the end with a separating blank line.
	const trimmed = fileContent.replace(/\n+$/, "")
	return trimmed ? `${trimmed}\n\n${block}\n` : `${block}\n`
}

// ---------------------------------------------------------------------------
// File I/O (kept separate from the logic so it's testable without disk)
// ---------------------------------------------------------------------------

export async function writeWikiMapToFile(
	filePath: string,
	block: string,
): Promise<void> {
	const fs = await import("node:fs")
	let existing = ""
	try {
		existing = fs.readFileSync(filePath, "utf-8")
	} catch (err) {
		// Only treat ENOENT (file doesn't exist) as create-new; rethrow other
		// errors (EACCES, EISDIR) so they surface instead of being masked (L1).
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err
	}
	const updated = injectWikiMapBlock(existing, block)
	fs.writeFileSync(filePath, updated, "utf-8")
}

export async function generateAndWriteWikiMap(
	handle: WikiDbHandle,
	targetFiles: string[],
	opts: MapPointerOptions = {},
): Promise<{ files: string[]; block: string }> {
	const block = await generateWikiMapBlock(handle, opts)
	for (const f of targetFiles) {
		await writeWikiMapToFile(f, block)
	}
	return { files: targetFiles, block }
}
