import fs from "node:fs/promises"
import path from "node:path"
import type {
	ClientSession,
	Collection,
	Db,
	Document,
	MongoClient,
} from "mongodb"
import {
	type MemoryMongoDBEmbeddingMode,
	createSubsystemLogger,
} from "@mdbrain/lib"
import {
	buildFileEntry,
	chunkMarkdown,
	listMemoryFiles,
	type MemoryChunk,
	type MemoryFileEntry,
} from "./internal.js"
import type { EmbeddingStatus } from "./mongodb-embedding-retry.js"
import { chunksCollection, filesCollection } from "./mongodb-schema.js"
import { resolveScopeRef } from "./mongodb-scope.js"
import {
	buildSessionEntry,
	listSessionFilesForAgent,
	type SessionFileEntry,
} from "./session-files.js"
import type {
	InternalMemoryStoredSource,
	MemorySyncProgressUpdate,
} from "./types.js"

const log = createSubsystemLogger("memory:mongodb:sync")

// Re-export chunk helpers from internal.ts
export { chunkMarkdown }

// ---------------------------------------------------------------------------
// File metadata operations
// ---------------------------------------------------------------------------

type SyncNamespace = {
	source: InternalMemoryStoredSource
	agentId?: string
	scope?: string
	scopeRef?: string
}

function buildNamespaceFilter(namespace: SyncNamespace): Document {
	const filter: Document = { source: namespace.source }
	if (namespace.agentId) {
		filter.agentId = namespace.agentId
	}
	if (namespace.scope) {
		filter.scope = namespace.scope
	}
	if (namespace.scopeRef) {
		filter.scopeRef = namespace.scopeRef
	}
	return filter
}

function buildStorageId(namespace: SyncNamespace, relPath: string): string {
	return [
		namespace.source,
		namespace.agentId ?? "_",
		namespace.scope ?? "_",
		namespace.scopeRef ?? "_",
		relPath,
	].join("::")
}

async function getStoredFiles(
	files: Collection,
	namespace: SyncNamespace,
): Promise<Map<string, { hash: string; mtime: number; size: number }>> {
	const docs = await files.find(buildNamespaceFilter(namespace)).toArray()
	const map = new Map<string, { hash: string; mtime: number; size: number }>()
	for (const doc of docs) {
		const relPath = typeof doc.path === "string" ? doc.path : String(doc._id)
		map.set(relPath, {
			hash: doc.hash as string,
			mtime: doc.mtime as number,
			size: doc.size as number,
		})
	}
	return map
}

async function upsertFileMetadata(
	files: Collection,
	entry: MemoryFileEntry,
	namespace: SyncNamespace,
	session?: ClientSession,
): Promise<void> {
	const update = {
		$set: {
			path: entry.path,
			source: namespace.source,
			...(namespace.agentId ? { agentId: namespace.agentId } : {}),
			...(namespace.scope ? { scope: namespace.scope } : {}),
			...(namespace.scopeRef ? { scopeRef: namespace.scopeRef } : {}),
			hash: entry.hash,
			mtime: entry.mtimeMs,
			size: entry.size,
			updatedAt: new Date(),
		},
	}
	const filter = { _id: buildStorageId(namespace, entry.path) } as Record<
		string,
		unknown
	>
	if (session) {
		await files.updateOne(filter, update, { upsert: true, session })
	} else {
		await files.updateOne(filter, update, { upsert: true })
	}
}

// ---------------------------------------------------------------------------
// Chunk operations
// ---------------------------------------------------------------------------

function buildChunkId(
	storageId: string,
	startLine: number,
	endLine: number,
): string {
	return `${storageId}:${startLine}:${endLine}`
}

async function upsertChunks(
	chunks: Collection,
	path: string,
	namespace: SyncNamespace,
	chunkList: MemoryChunk[],
	model: string,
	embeddings: number[][] | null,
	embeddingStatus: EmbeddingStatus,
	session?: ClientSession,
): Promise<number> {
	if (chunkList.length === 0) {
		return 0
	}

	const ops = chunkList.map((chunk, index) => {
		const chunkId = buildChunkId(
			buildStorageId(namespace, path),
			chunk.startLine,
			chunk.endLine,
		)
		const setDoc: Document = {
			path,
			source: namespace.source,
			...(namespace.agentId ? { agentId: namespace.agentId } : {}),
			...(namespace.scope ? { scope: namespace.scope } : {}),
			...(namespace.scopeRef ? { scopeRef: namespace.scopeRef } : {}),
			startLine: chunk.startLine,
			endLine: chunk.endLine,
			hash: chunk.hash,
			model,
			text: chunk.text,
			embeddingStatus,
			updatedAt: new Date(),
		}
		// Embeddings are generated by MongoDB automatically after write time.
		if (embeddings && embeddings[index]) {
			setDoc.embedding = embeddings[index]
		}
		return {
			updateOne: {
				filter: { _id: chunkId } as Record<string, unknown>,
				update: { $set: setDoc },
				upsert: true,
			},
		}
	})

	const result = session
		? await chunks.bulkWrite(ops, { ordered: false, session })
		: await chunks.bulkWrite(ops, { ordered: false })
	return result.upsertedCount + result.modifiedCount
}

async function deleteChunksForPath(
	chunks: Collection,
	path: string,
	namespace: SyncNamespace,
	session?: ClientSession,
): Promise<number> {
	const filter = { ...buildNamespaceFilter(namespace), path }
	const result = session
		? await chunks.deleteMany(filter, { session })
		: await chunks.deleteMany(filter)
	return result.deletedCount
}

async function deleteStaleChunks(
	chunks: Collection,
	namespace: SyncNamespace,
	validPaths: Set<string>,
	session?: ClientSession,
): Promise<number> {
	const namespaceFilter = buildNamespaceFilter(namespace)
	const allPaths = session
		? await chunks.distinct("path", namespaceFilter, { session })
		: await chunks.distinct("path", namespaceFilter)
	const stalePaths = allPaths.filter((p) => !validPaths.has(p))
	if (stalePaths.length === 0) {
		return 0
	}

	const filter = { ...namespaceFilter, path: { $in: stalePaths } }
	const result = session
		? await chunks.deleteMany(filter, { session })
		: await chunks.deleteMany(filter)
	return result.deletedCount
}

// ---------------------------------------------------------------------------
// Transaction helpers
// ---------------------------------------------------------------------------

/**
 * Detect if an error indicates transactions are not supported (standalone topology).
 * Transactions require a replica set or mongos.
 */
function isTransactionNotSupported(err: unknown): boolean {
	if (err instanceof Error && "code" in err) {
		const code = (err as { code: number }).code
		// 20 = IllegalOperation (standalone), 263 = NoSuchTransaction
		if (code === 20 || code === 263) {
			return true
		}
	}
	const msg = err instanceof Error ? err.message : String(err)
	return msg.includes("Transaction numbers are only allowed on a replica set")
}

// ---------------------------------------------------------------------------
// Atomic file sync
// ---------------------------------------------------------------------------

async function syncFileAtomically(params: {
	client: MongoClient | undefined
	useTransactions: boolean
	chunksCol: Collection
	filesCol: Collection
	file: MemoryFileEntry
	namespace: SyncNamespace
	chunks: MemoryChunk[]
	model: string
	embeddings: number[][] | null
	embeddingStatus: EmbeddingStatus
}): Promise<{ upserted: number; disableTransactions: boolean }> {
	const {
		client,
		chunksCol,
		filesCol,
		file,
		namespace,
		chunks,
		model,
		embeddings,
		embeddingStatus,
	} = params

	if (!client || !params.useTransactions) {
		await deleteChunksForPath(chunksCol, file.path, namespace)
		const upserted = await upsertChunks(
			chunksCol,
			file.path,
			namespace,
			chunks,
			model,
			embeddings,
			embeddingStatus,
		)
		await upsertFileMetadata(filesCol, file, namespace)
		return { upserted, disableTransactions: false }
	}

	const session = client.startSession()
	try {
		let upserted = 0
		await session.withTransaction(
			async () => {
				await deleteChunksForPath(chunksCol, file.path, namespace, session)
				upserted = await upsertChunks(
					chunksCol,
					file.path,
					namespace,
					chunks,
					model,
					embeddings,
					embeddingStatus,
					session,
				)
				await upsertFileMetadata(filesCol, file, namespace, session)
			},
			{ writeConcern: { w: "majority" } },
		)
		return { upserted, disableTransactions: false }
	} catch (err) {
		if (isTransactionNotSupported(err)) {
			log.info(
				"transactions not supported (standalone), falling back for file sync",
			)
			await deleteChunksForPath(chunksCol, file.path, namespace)
			const upserted = await upsertChunks(
				chunksCol,
				file.path,
				namespace,
				chunks,
				model,
				embeddings,
				embeddingStatus,
			)
			await upsertFileMetadata(filesCol, file, namespace)
			return { upserted, disableTransactions: true }
		}
		throw err
	} finally {
		await session.endSession()
	}
}

// ---------------------------------------------------------------------------
// Main sync function
// ---------------------------------------------------------------------------

export type SyncResult = {
	filesProcessed: number
	chunksUpserted: number
	staleDeleted: number
	sessionFilesProcessed: number
	sessionChunksUpserted: number
}

export async function syncToMongoDB(params: {
	client?: MongoClient
	db: Db
	prefix: string
	agentId?: string
	sessionMemoryEnabled?: boolean
	workspaceDir: string
	extraPaths?: string[]
	embeddingMode: MemoryMongoDBEmbeddingMode
	chunking?: { tokens: number; overlap: number }
	model?: string
	reason?: string
	force?: boolean
	maxSessionChunks?: number
	progress?: (update: MemorySyncProgressUpdate) => void
}): Promise<SyncResult> {
	const { db, prefix, embeddingMode, progress } = params
	const model = params.model ?? "voyage-4-large"
	const chunking = params.chunking ?? { tokens: 400, overlap: 80 }
	const memoryNamespace: SyncNamespace = {
		source: "conversation",
		...(params.agentId ? { agentId: params.agentId } : {}),
		scope: "workspace",
		scopeRef: resolveScopeRef({
			scope: "workspace",
			agentId: params.agentId ?? "__workspace__",
			workspaceDir: params.workspaceDir,
		}),
	}
	// Track whether transactions are available (disabled on first standalone error)
	let useTransactions = !!params.client

	const chunksCol = chunksCollection(db, prefix)
	const filesCol = filesCollection(db, prefix)

	// 2. Get stored file metadata from MongoDB
	const storedFiles = await getStoredFiles(filesCol, memoryNamespace)

	// =========================================================================
	// Phase A: Memory files (source="memory")
	// =========================================================================

	// 1. List memory files on disk (returns absolute paths)
	const diskPaths = await listMemoryFiles(
		params.workspaceDir,
		params.extraPaths,
	)
	log.info(
		`sync: found ${diskPaths.length} memory files on disk (reason=${params.reason ?? "manual"})`,
	)

	// Build file entries with hash, mtime, size
	const diskFiles: MemoryFileEntry[] = []
	for (const absPath of diskPaths) {
		try {
			const entry = await buildFileEntry(absPath, params.workspaceDir)
			if (entry) {
				diskFiles.push(entry)
			}
		} catch (err) {
			const msg = err instanceof Error ? err.message : String(err)
			log.warn(`sync: failed to read ${absPath}: ${msg}`)
		}
	}

	// Determine which files need re-indexing
	const filesToProcess: MemoryFileEntry[] = []
	const validPaths = new Set<string>()

	for (const file of diskFiles) {
		validPaths.add(file.path)
		const stored = storedFiles.get(file.path)
		if (params.force || !stored || stored.hash !== file.hash) {
			filesToProcess.push(file)
		}
	}

	log.info(
		`sync: ${filesToProcess.length}/${diskPaths.length} memory files need re-indexing`,
	)
	progress?.({
		completed: 0,
		total: filesToProcess.length,
		label: "Syncing memory files",
	})

	// Process each changed memory file
	let filesProcessed = 0
	let totalChunksUpserted = 0

	for (const file of filesToProcess) {
		try {
			const content = await fs.readFile(file.absPath, "utf-8")
			const chunks = chunkMarkdown(content, chunking)

			// Text-only write path — embeddings are generated by MongoDB automatically
			const embeddingStatus: EmbeddingStatus = "pending"
			const embeddings: number[][] | null = null

			const { upserted, disableTransactions } = await syncFileAtomically({
				client: params.client,
				useTransactions,
				chunksCol,
				filesCol,
				file,
				namespace: memoryNamespace,
				chunks,
				model,
				embeddings,
				embeddingStatus,
			})
			totalChunksUpserted += upserted
			if (disableTransactions) {
				useTransactions = false
			}

			filesProcessed++
			progress?.({
				completed: filesProcessed,
				total: filesToProcess.length,
				label: file.path,
			})
		} catch (err) {
			const msg = err instanceof Error ? err.message : String(err)
			log.warn(`sync: failed to process ${file.path}: ${msg}`)
		}
	}

	// =========================================================================
	// Phase B: Session transcript files (runtime conversation history)
	// =========================================================================

	let sessionFilesProcessed = 0
	let sessionChunksUpserted = 0
	let sessionStaleDeleted = 0

	if (params.agentId && params.sessionMemoryEnabled !== false) {
		try {
			const sessionResult = await syncSessionFiles({
				client: params.client,
				useTransactions,
				agentId: params.agentId,
				chunksCol,
				filesCol,
				storedFiles: await getStoredFiles(filesCol, {
					source: "sessions",
					agentId: params.agentId,
					scope: "agent",
					scopeRef: resolveScopeRef({
						scope: "agent",
						agentId: params.agentId,
					}),
				}),
				validPaths,
				embeddingMode,
				chunking,
				model,
				force: params.force,
				maxSessionChunks: params.maxSessionChunks,
				progress,
			})
			sessionFilesProcessed = sessionResult.filesProcessed
			sessionChunksUpserted = sessionResult.chunksUpserted
			sessionStaleDeleted = sessionResult.staleDeleted
			// Propagate standalone detection from session sync to stale cleanup
			if (!sessionResult.useTransactions) {
				useTransactions = false
			}
		} catch (err) {
			const msg = err instanceof Error ? err.message : String(err)
			log.warn(`session sync failed: ${msg}`)
		}
	}

	// =========================================================================
	// Phase C: Stale cleanup (covers markdown paths and active conversation paths)
	// =========================================================================

	// Compute stale paths OUTSIDE any transaction (avoid read pressure inside txn)
	const staleFileIds: string[] = []
	for (const [storedPath] of storedFiles) {
		if (!validPaths.has(storedPath)) {
			staleFileIds.push(buildStorageId(memoryNamespace, storedPath))
		}
	}

	let staleDeleted = 0
	if (params.client && useTransactions) {
		let session: ClientSession | undefined
		try {
			session = params.client.startSession()
			await session.withTransaction(
				async () => {
					staleDeleted = await deleteStaleChunks(
						chunksCol,
						memoryNamespace,
						validPaths,
						session,
					)
					if (staleFileIds.length > 0) {
						await filesCol.deleteMany(
							{ _id: { $in: staleFileIds } } as Record<string, unknown>,
							{
								session,
							},
						)
					}
				},
				{ writeConcern: { w: "majority" } },
			)
		} catch (err) {
			if (isTransactionNotSupported(err)) {
				// Fallback: non-transactional stale cleanup
				staleDeleted = await deleteStaleChunks(
					chunksCol,
					memoryNamespace,
					validPaths,
				)
				if (staleFileIds.length > 0) {
					await filesCol.deleteMany({ _id: { $in: staleFileIds } } as Record<
						string,
						unknown
					>)
				}
			} else {
				throw err
			}
		} finally {
			await session?.endSession()
		}
	} else {
		staleDeleted = await deleteStaleChunks(
			chunksCol,
			memoryNamespace,
			validPaths,
		)
		if (staleFileIds.length > 0) {
			await filesCol.deleteMany({ _id: { $in: staleFileIds } } as Record<
				string,
				unknown
			>)
		}
	}

	if (staleDeleted > 0) {
		log.info(`sync: removed ${staleDeleted} stale chunks`)
	}
	if (sessionStaleDeleted > 0) {
		log.info(`sync: removed ${sessionStaleDeleted} stale session chunks`)
	}

	log.info(
		`sync complete: memory=${filesProcessed} conversation=${sessionFilesProcessed} chunks=${totalChunksUpserted + sessionChunksUpserted} stale=${staleDeleted + sessionStaleDeleted}`,
	)

	return {
		filesProcessed,
		chunksUpserted: totalChunksUpserted,
		staleDeleted: staleDeleted + sessionStaleDeleted,
		sessionFilesProcessed,
		sessionChunksUpserted,
	}
}

// ---------------------------------------------------------------------------
// Session file sync
// ---------------------------------------------------------------------------

async function syncSessionFiles(params: {
	client?: MongoClient
	useTransactions: boolean
	agentId: string
	chunksCol: Collection
	filesCol: Collection
	storedFiles: Map<string, { hash: string; mtime: number; size: number }>
	validPaths: Set<string>
	embeddingMode: MemoryMongoDBEmbeddingMode
	chunking: { tokens: number; overlap: number }
	model: string
	force?: boolean
	maxSessionChunks?: number
	progress?: (update: MemorySyncProgressUpdate) => void
}): Promise<{
	filesProcessed: number
	chunksUpserted: number
	staleDeleted: number
	useTransactions: boolean
}> {
	const sessionNamespace: SyncNamespace = {
		source: "sessions",
		agentId: params.agentId,
		scope: "agent",
		scopeRef: resolveScopeRef({ scope: "agent", agentId: params.agentId }),
	}
	const sessionPaths = await listSessionFilesForAgent(params.agentId)
	if (sessionPaths.length === 0) {
		return {
			filesProcessed: 0,
			chunksUpserted: 0,
			staleDeleted: 0,
			useTransactions: params.useTransactions,
		}
	}

	log.info(`sync: found ${sessionPaths.length} session files`)
	let filesProcessed = 0
	let chunksUpserted = 0
	let useTransactions = params.useTransactions
	params.progress?.({
		completed: 0,
		total: sessionPaths.length,
		label: "Syncing MongoDB conversation transcripts…",
	})

	for (const absPath of sessionPaths) {
		try {
			const entry = await buildSessionEntry(absPath)
			if (!entry || !entry.content) {
				params.progress?.({
					completed: filesProcessed,
					total: sessionPaths.length,
					label: `Skipping empty conversation transcript (${path.basename(absPath)})`,
				})
				continue
			}

			// Track this session path as valid (for stale cleanup)
			params.validPaths.add(entry.path)

			// Check if already indexed with same hash
			const stored = params.storedFiles.get(entry.path)
			if (!params.force && stored?.hash === entry.hash) {
				params.progress?.({
					completed: filesProcessed,
					total: sessionPaths.length,
					label: `Conversation transcript already indexed (${path.basename(absPath)})`,
				})
				continue
			}

			// Chunk the session content (same as memory files)
			let chunks = chunkMarkdown(entry.content, params.chunking)

			// Cap session chunks at maxSessionChunks — keep last N (most recent) chunks
			if (
				params.maxSessionChunks &&
				params.maxSessionChunks > 0 &&
				chunks.length > params.maxSessionChunks
			) {
				log.info(
					`session ${entry.path}: truncating ${chunks.length} chunks to last ${params.maxSessionChunks}`,
				)
				chunks = chunks.slice(-params.maxSessionChunks)
			}

			// Session chunks follow the same text-only write path as memory files.
			const embeddingStatus: EmbeddingStatus = "pending"
			const embeddings: number[][] | null = null

			// Atomic write: delete + upsert + metadata (reuse syncFileAtomically)
			const { upserted, disableTransactions } = await syncSessionFileAtomically(
				{
					client: params.client,
					useTransactions,
					chunksCol: params.chunksCol,
					filesCol: params.filesCol,
					entry,
					namespace: sessionNamespace,
					chunks,
					model: params.model,
					embeddings,
					embeddingStatus,
				},
			)
			chunksUpserted += upserted
			if (disableTransactions) {
				useTransactions = false
			}
			filesProcessed++
			params.progress?.({
				completed: filesProcessed,
				total: sessionPaths.length,
				label: `Indexed conversation transcript ${filesProcessed}/${sessionPaths.length}`,
			})
		} catch (err) {
			const msg = err instanceof Error ? err.message : String(err)
			log.warn(`session sync failed for ${absPath}: ${msg}`)
			params.progress?.({
				completed: filesProcessed,
				total: sessionPaths.length,
				label: `Conversation transcript sync failed (${path.basename(absPath)})`,
			})
		}
	}

	const staleSessionPaths = Array.from(params.storedFiles.keys()).filter(
		(storedPath) => !params.validPaths.has(storedPath),
	)
	let staleDeleted = 0
	if (staleSessionPaths.length > 0) {
		staleDeleted = await deleteStaleChunks(
			params.chunksCol,
			sessionNamespace,
			new Set(params.validPaths),
		)
		await params.filesCol.deleteMany({
			_id: {
				$in: staleSessionPaths.map((storedPath) =>
					buildStorageId(sessionNamespace, storedPath),
				),
			},
		} as Record<string, unknown>)
	}

	log.info(
		`sync: sessions processed=${filesProcessed} chunks=${chunksUpserted} stale=${staleDeleted}`,
	)
	return { filesProcessed, chunksUpserted, staleDeleted, useTransactions }
}

/** Atomic session file sync — same pattern as syncFileAtomically but for SessionFileEntry. */
async function syncSessionFileAtomically(params: {
	client: MongoClient | undefined
	useTransactions: boolean
	chunksCol: Collection
	filesCol: Collection
	entry: SessionFileEntry
	namespace: SyncNamespace
	chunks: MemoryChunk[]
	model: string
	embeddings: number[][] | null
	embeddingStatus: EmbeddingStatus
}): Promise<{ upserted: number; disableTransactions: boolean }> {
	const {
		client,
		chunksCol,
		filesCol,
		entry,
		namespace,
		chunks,
		model,
		embeddings,
		embeddingStatus,
	} = params

	if (!client || !params.useTransactions) {
		await deleteChunksForPath(chunksCol, entry.path, namespace)
		const upserted = await upsertChunks(
			chunksCol,
			entry.path,
			namespace,
			chunks,
			model,
			embeddings,
			embeddingStatus,
		)
		await upsertSessionFileMetadata(filesCol, entry, namespace)
		return { upserted, disableTransactions: false }
	}

	const session = client.startSession()
	try {
		let upserted = 0
		await session.withTransaction(
			async () => {
				await deleteChunksForPath(chunksCol, entry.path, namespace, session)
				upserted = await upsertChunks(
					chunksCol,
					entry.path,
					namespace,
					chunks,
					model,
					embeddings,
					embeddingStatus,
					session,
				)
				await upsertSessionFileMetadata(filesCol, entry, namespace, session)
			},
			{ writeConcern: { w: "majority" } },
		)
		return { upserted, disableTransactions: false }
	} catch (err) {
		if (isTransactionNotSupported(err)) {
			log.info(
				"transactions not supported (standalone), falling back for session sync",
			)
			await deleteChunksForPath(chunksCol, entry.path, namespace)
			const upserted = await upsertChunks(
				chunksCol,
				entry.path,
				namespace,
				chunks,
				model,
				embeddings,
				embeddingStatus,
			)
			await upsertSessionFileMetadata(filesCol, entry, namespace)
			return { upserted, disableTransactions: true }
		}
		throw err
	} finally {
		await session.endSession()
	}
}

async function upsertSessionFileMetadata(
	files: Collection,
	entry: SessionFileEntry,
	namespace: SyncNamespace,
	session?: ClientSession,
): Promise<void> {
	const update = {
		$set: {
			path: entry.path,
			source: namespace.source,
			...(namespace.agentId ? { agentId: namespace.agentId } : {}),
			...(namespace.scope ? { scope: namespace.scope } : {}),
			...(namespace.scopeRef ? { scopeRef: namespace.scopeRef } : {}),
			hash: entry.hash,
			mtime: entry.mtimeMs,
			size: entry.size,
			updatedAt: new Date(),
		},
	}
	const filter = { _id: buildStorageId(namespace, entry.path) } as Record<
		string,
		unknown
	>
	if (session) {
		await files.updateOne(filter, update, { upsert: true, session })
	} else {
		await files.updateOne(filter, update, { upsert: true })
	}
}
